export const scoreboard = {
    PUSH_REQUEST: 'SCOREBOARD_PUSH_REQUEST',
    PUSH_SUCCESS: 'SCOREBOARD_PUSH_SUCCESS',
    PUSH_FAILURE: 'SCOREBOARD_PUSH_FAILURE',

    GET_ALL_REQUEST: 'SCOREBOARD_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'SCOREBOARD_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'SCOREBOARD_GET_ALL_FAILURE',

    UPDATE_REQUEST: 'SCOREBOARD_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'SCOREBOARD_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'SCOREBOARD_UPDATE_FAILURE',

    REMOVE_REQUEST: 'SCOREBOARD_REMOVE_REQUEST',
    REMOVE_SUCCESS: 'SCOREBOARD_REMOVE_SUCCESS',
    REMOVE_FAILURE: 'SCOREBOARD_REMOVE_FAILURE',
};
